"""create users table

Revision ID: 098b766add86
Revises: 
Create Date: 2026-04-13 21:19:41.673759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098b766add86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email пользователя (логин)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хеш пароля (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Полное имя пользователя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли email'),
    sa.Column('role', sa.Enum('ADMIN', 'ENTREPRENEUR', 'GUEST', name='userrole'), nullable=False, comment='Роль пользователя'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Название компании (если есть)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Контактный телефон'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего входа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
