from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f79d4754ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст вопроса'),
    sa.Column('category', sa.Enum('SWOT_STRENGTH', 'SWOT_WEAKNESS', 'SWOT_OPPORTUNITY', 'SWOT_THREAT', 'PEST_POLITICAL', 'PEST_ECONOMIC', 'PEST_SOCIAL', 'PEST_TECHNOLOGICAL', 'FREE_FORM', name='questioncategory'), nullable=False, comment='Категория вопроса (SWOT/PEST/свободный)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Порядок отображения'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='Обязательный ли вопрос'),
    sa.Column('hint', sa.Text(), nullable=True, comment='Подсказка к вопросу'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email пользователя (логин)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хеш пароля (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Полное имя пользователя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли email'),
    sa.Column('role', sa.Enum('ADMIN', 'ENTREPRENEUR', 'GUEST', name='userrole'), nullable=False, comment='Роль пользователя'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Название компании (если есть)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Контактный телефон'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего входа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название проекта'),
    sa.Column('description', sa.Text(), nullable=True, comment='Краткое описание'),
    sa.Column('sphere', sa.Enum('RETAIL', 'SERVICES', 'PRODUCTION', 'IT', 'CONSTRUCTION', 'LOGISTICS', 'FINANCE', 'OTHER', name='businesssphere'), nullable=False, comment='Сфера бизнеса'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_ANALYSIS', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False, comment='Статус проекта'),
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='ID владельца проекта'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('risk_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Пользователь, проходящий анализ'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='Проект для анализа'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False, comment='Статус анализа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_analyses_id'), 'risk_analyses', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст ответа (свободная форма)'),
    sa.Column('analysis_id', sa.String(length=36), nullable=False, comment='Сессия анализа'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='Вопрос анкеты'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['risk_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Название риска'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробное описание риска'),
    sa.Column('category', sa.Enum('OPERATIONAL', 'FINANCIAL', 'PERSONNEL', 'LEGAL', 'MARKET', 'REPUTATIONAL', 'IT', name='riskcategory'), nullable=False, comment='Категория риска'),
    sa.Column('probability', sa.Integer(), nullable=False, comment='Вероятность (1-5)'),
    sa.Column('impact', sa.Integer(), nullable=False, comment='Влияние (1-5)'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskpriority'), nullable=True, comment='Приоритет (вычисляется как P × I)'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID проекта'),
    sa.Column('analysis_id', sa.String(length=36), nullable=True, comment='ID сессии анализа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['risk_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_risk_analyses_id'), table_name='risk_analyses')
    op.drop_table('risk_analyses')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
