"""таблицы опросника

Revision ID: 94a2e7afb2f0
Revises: fb84cc548efd
Create Date: 2026-05-03 20:04:09.883924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a2e7afb2f0'
down_revision: Union[str, None] = 'fb84cc548efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст вопроса'),
    sa.Column('category', sa.Enum('SWOT_STRENGTH', 'SWOT_WEAKNESS', 'SWOT_OPPORTUNITY', 'SWOT_THREAT', 'PEST_POLITICAL', 'PEST_ECONOMIC', 'PEST_SOCIAL', 'PEST_TECHNOLOGICAL', 'FREE_FORM', name='questioncategory'), nullable=False, comment='Категория вопроса (SWOT/PEST/свободный)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Порядок отображения'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='Обязательный ли вопрос'),
    sa.Column('hint', sa.Text(), nullable=True, comment='Подсказка к вопросу'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('risk_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Пользователь, проходящий анализ'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='Проект для анализа'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False, comment='Статус анализа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_analyses_id'), 'risk_analyses', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст ответа (свободная форма)'),
    sa.Column('analysis_id', sa.String(length=36), nullable=False, comment='Сессия анализа'),
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='Вопрос анкеты'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['risk_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_foreign_key(None, 'risks', 'risk_analyses', ['analysis_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_risk_analyses_id'), table_name='risk_analyses')
    op.drop_table('risk_analyses')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
