"""добавляем риск и проект таблицы

Revision ID: fb84cc548efd
Revises: 098b766add86
Create Date: 2026-05-03 14:58:40.464103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb84cc548efd'
down_revision: Union[str, None] = '098b766add86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название проекта'),
    sa.Column('description', sa.Text(), nullable=True, comment='Краткое описание'),
    sa.Column('sphere', sa.Enum('RETAIL', 'SERVICES', 'PRODUCTION', 'IT', 'CONSTRUCTION', 'LOGISTICS', 'FINANCE', 'OTHER', name='businesssphere'), nullable=False, comment='Сфера бизнеса'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_ANALYSIS', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False, comment='Статус проекта'),
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='ID владельца проекта'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Название риска'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробное описание риска'),
    sa.Column('category', sa.Enum('OPERATIONAL', 'FINANCIAL', 'PERSONNEL', 'LEGAL', 'MARKET', 'REPUTATIONAL', 'IT', name='riskcategory'), nullable=False, comment='Категория риска'),
    sa.Column('probability', sa.Integer(), nullable=False, comment='Вероятность (1-5)'),
    sa.Column('impact', sa.Integer(), nullable=False, comment='Влияние (1-5)'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskpriority'), nullable=True, comment='Приоритет (вычисляется как P × I)'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='ID проекта'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
